### PR TITLE
Store field type in map attribute column

### PR DESCRIPTION
**Pull request by pdelewski**
At some point we introduced `attributes_string_type` to not lose already inferred field type. 
With refactoring to maps we lost that. Now it's time to bring it back so `attribute` map has been extended
from `Map(String,String)` to `Map(String,Array(String))`

image

### CODE REVIEW

**Comment by avelanarius** [comment]
Have you considered changing the type to `Map(String, Tuple(String, String))`? It would be more strongly typed and maybe has some performance/usability benefits?

**Comment by pdelewski** [comment]
> Have you considered changing the type to `Map(String, Tuple(String, String))`? It would be more strongly typed and maybe has some performance/usability benefits?

Yes, that's another option. For now we know that `Map(String,Array(String)` works but I can check Map(String, Tuple(String,String) to check how much work is required to do so.

**Comment by pdelewski** [comment]
Few solutions considered:
- Map(String,Array(String))
- Map(String,Tuple(String,String))
- separate maps for values and types Map(String,String)

**Comment by pdelewski** [comment]
Closing due to https://github.com/QuesmaOrg/quesma/pull/691

**Pull request closed without merging**
